import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

export type PersonaWhereInput = {
  ageRange?: StringNullableFilter;
  attitudes?: StringNullableFilter;
  careerPath?: StringNullableFilter;
  challengesAndPainPoints?: StringNullableFilter;
  children?: StringNullableFilter;
  communicationChannels?: StringNullableFilter;
  competitorProducts?: StringNullableFilter;
  completed?: StringNullableFilter;
  culturalAndSocialInfluences?: StringNullableFilter;
  currentlyPursuing?: StringNullableFilter;
  definition?: StringNullableFilter;
  does?: StringNullableFilter;
  familyStatus?: StringNullableFilter;
  featureAnalysis?: StringNullableFilter;
  feels?: StringNullableFilter;
  gender?: StringNullableFilter;
  generalLifestyle?: StringNullableFilter;
  hobbiesAndInterests?: StringNullableFilter;
  id?: StringFilter;
  incomeLevel?: StringNullableFilter;
  location?: StringNullableFilter;
  mediaChannels?: StringNullableFilter;
  missingFeatures?: StringNullableFilter;
  motivationsAndDesires?: StringNullableFilter;
  name?: StringNullableFilter;
  needs?: StringNullableFilter;
  occupation?: StringNullableFilter;
  otherHabits?: StringNullableFilter;
  personaAge?: IntNullableFilter;
  productPreferences?: StringNullableFilter;
  satisfactionLevels?: StringNullableFilter;
  says?: StringNullableFilter;
  technologyUsage?: StringNullableFilter;
  thinks?: StringNullableFilter;
  valuedFeatures?: StringNullableFilter;
  values?: StringNullableFilter;
  wantsAndGoals?: StringNullableFilter;
};
