import { SortOrder } from "../../util/SortOrder";

export type PersonaOrderByInput = {
  ageRange?: SortOrder;
  attitudes?: SortOrder;
  careerPath?: SortOrder;
  challengesAndPainPoints?: SortOrder;
  children?: SortOrder;
  communicationChannels?: SortOrder;
  competitorProducts?: SortOrder;
  completed?: SortOrder;
  createdAt?: SortOrder;
  culturalAndSocialInfluences?: SortOrder;
  currentlyPursuing?: SortOrder;
  definition?: SortOrder;
  does?: SortOrder;
  familyStatus?: SortOrder;
  featureAnalysis?: SortOrder;
  feels?: SortOrder;
  gender?: SortOrder;
  generalLifestyle?: SortOrder;
  hobbiesAndInterests?: SortOrder;
  id?: SortOrder;
  incomeLevel?: SortOrder;
  location?: SortOrder;
  mediaChannels?: SortOrder;
  missingFeatures?: SortOrder;
  motivationsAndDesires?: SortOrder;
  name?: SortOrder;
  needs?: SortOrder;
  occupation?: SortOrder;
  otherHabits?: SortOrder;
  personaAge?: SortOrder;
  productPreferences?: SortOrder;
  satisfactionLevels?: SortOrder;
  says?: SortOrder;
  technologyUsage?: SortOrder;
  thinks?: SortOrder;
  updatedAt?: SortOrder;
  valuedFeatures?: SortOrder;
  values?: SortOrder;
  wantsAndGoals?: SortOrder;
};
