export type Persona = {
  ageRange: string | null;
  attitudes: string | null;
  careerPath: string | null;
  challengesAndPainPoints: string | null;
  children: string | null;
  communicationChannels: string | null;
  competitorProducts: string | null;
  completed: string | null;
  createdAt: Date;
  culturalAndSocialInfluences: string | null;
  currentlyPursuing: string | null;
  definition: string | null;
  does: string | null;
  familyStatus: string | null;
  featureAnalysis: string | null;
  feels: string | null;
  gender: string | null;
  generalLifestyle: string | null;
  hobbiesAndInterests: string | null;
  id: string;
  incomeLevel: string | null;
  location: string | null;
  mediaChannels: string | null;
  missingFeatures: string | null;
  motivationsAndDesires: string | null;
  name: string | null;
  needs: string | null;
  occupation: string | null;
  otherHabits: string | null;
  personaAge: number | null;
  productPreferences: string | null;
  satisfactionLevels: string | null;
  says: string | null;
  technologyUsage: string | null;
  thinks: string | null;
  updatedAt: Date;
  valuedFeatures: string | null;
  values: string | null;
  wantsAndGoals: string | null;
};
